import { lstatSync, readFileSync, writeFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

const MARKER_TEXT = "generated by claude-repo-skills; do not edit";
const MARKER = `<!-- ${MARKER_TEXT} -->`;

function escapeYamlValue(value) {
  return String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\r\n", "\\n")
    .replaceAll("\n", "\\n")
    .replaceAll("\r", "\\n");
}

function frontmatter(name, description) {
  return `---\nname: ${escapeYamlValue(name)}\ndescription: "${escapeYamlValue(description)}"\n---`;
}

function bullets(values, empty = "None discovered.") {
  return values.length ? values.map((value) => `- \`${value}\``).join("\n") : empty;
}

function commands(analysis, wanted) {
  const scripts = analysis.package?.scripts ?? {};
  const matched = wanted.filter((name) => scripts[name]);
  if (!matched.length) return "Use the repository-native validation commands.";

  const pm = analysis.packageManager;
  if (!pm) {
    const fallback = matched.map((name) => `- \`npm run ${name}\``).join("\n");
    return `No lockfile was detected, so the package manager is unknown. Falling back to npm; substitute the actual package manager if different.\n\n${fallback}`;
  }
  // `bun test` runs bun's native test runner, not a package.json script.
  // Script-backed commands under bun must go through `bun run`.
  const prefix = pm === "npm" ? "npm run" : pm === "bun" ? "bun run" : pm;
  return matched.map((name) => `- \`${prefix} ${name}\``).join("\n");
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// A plain substring match treats "test" as present inside "latest" or "contest" — false
// positives with no relation to testing. Requiring each keyword to start right after a path
// separator, a dot, a hyphen/underscore, or the beginning of the path keeps legitimate matches
// like "testing.md" or "unit-test.md" while rejecting those. `prefixes` stays a plain
// startsWith check for whole-subtree inclusion (e.g. every file under "docs/").
function selectedDocs(analysis, { keywords = [], prefixes = [] } = {}) {
  const boundary = "(?:^|[/.\\-_])";
  const patterns = keywords.map((keyword) => new RegExp(`${boundary}${escapeRegExp(keyword)}`, "i"));
  return Object.entries(analysis.documentContent)
    .filter(
      ([path]) =>
        prefixes.some((prefix) => path.startsWith(prefix)) ||
        patterns.some((pattern) => pattern.test(path)),
    )
    .map(([path, content]) => `## ${path}\n\n${content}`)
    .join("\n\n");
}

function openAiYaml(name, title, description) {
  return `# ${MARKER_TEXT}
interface:
  display_name: "${title}"
  short_description: "${description}"
  default_prompt: "Use $${name} to work with this repository."
`;
}

function buildFiles(analysis) {
  const files = new Map();
  const root = analysis.config.output;
  const stack = [
    `Repository: \`${analysis.name}\``,
    `Digest: \`${analysis.digest}\``,
    `Languages: ${Object.entries(analysis.languages).map(([name, count]) => `${name} (${count})`).join(", ") || "unknown"}`,
    `Manifests: ${analysis.manifests.map((name) => `\`${name}\``).join(", ") || "none"}`,
    `Package manager: \`${analysis.packageManager ?? "not detected"}\``,
  ].map((line) => `- ${line}`).join("\n");

  if (analysis.config.skills.includes("development")) {
    const name = "repo-development";
    files.set(`${root}/${name}/SKILL.md`, `${frontmatter(name, `Implement, refactor, or debug ${analysis.name} using its discovered architecture, module boundaries, stack, and repository conventions.`)}

${MARKER}

# Repository development

1. Read [references/repository.md](references/repository.md).
2. Inspect the target module and its public boundary.
3. Follow existing architecture and naming patterns.
4. Keep domain logic outside routing and presentation layers.
5. Add focused tests and run the repository quality gates.

Do not infer conventions when the repository documents them explicitly.
`);
    files.set(`${root}/${name}/references/repository.md`, `${MARKER}

# Repository map

${stack}

## Modules

${bullets(analysis.modules)}

## Package scripts

${bullets(Object.keys(analysis.package?.scripts ?? {}).sort())}

## Repository instructions

${selectedDocs(analysis, { keywords: ["AGENTS", "CLAUDE", "architecture", "code-style"] }) || "No explicit architecture instructions were discovered."}
`);
    files.set(`${root}/${name}/agents/openai.yaml`, openAiYaml(name, "Repository Development", "Follow repository architecture and conventions"));
  }

  if (analysis.config.skills.includes("domain")) {
    const name = "repo-domain";
    files.set(`${root}/${name}/SKILL.md`, `${frontmatter(name, `Design or change business behavior in ${analysis.name} using its product documentation, invariants, compliance boundaries, and domain vocabulary.`)}

${MARKER}

# Repository domain

1. Read [references/domain.md](references/domain.md).
2. Name the business invariant before changing behavior.
3. Preserve authorization, auditability, privacy, and transactional consistency.
4. Use fictitious data in tests and examples.
5. Document residual domain or compliance risk.
`);
    files.set(`${root}/${name}/references/domain.md`, `${MARKER}

# Domain context

Generated from repository documentation. Digest: \`${analysis.digest}\`.

${selectedDocs(analysis, {
  // AGENTS.md/CLAUDE.md deliberately excluded here: they already go into
  // repo-development/references/repository.md, and duplicating their full content into this
  // file too just bloats context for no added coverage.
  keywords: ["README", "domain", "product", "security", "compliance"],
  prefixes: ["docs/"],
}) || "No domain documentation was discovered."}
`);
    files.set(`${root}/${name}/agents/openai.yaml`, openAiYaml(name, "Repository Domain", "Apply product and domain invariants safely"));
  }

  if (analysis.config.skills.includes("quality")) {
    const name = "repo-quality";
    files.set(`${root}/${name}/SKILL.md`, `${frontmatter(name, `Validate, review, or prepare changes in ${analysis.name} using its actual test commands, CI expectations, security constraints, and completion gates.`)}

${MARKER}

# Repository quality

1. Read [references/quality.md](references/quality.md).
2. Run the smallest relevant test first.
3. Preserve the first useful failure and diagnose it.
4. Run all required gates before declaring completion.
5. Report every skipped check and its reason.
`);
    files.set(`${root}/${name}/references/quality.md`, `${MARKER}

# Quality map

Generated from repository sources. Digest: \`${analysis.digest}\`.

## Required commands

${commands(analysis, ["typecheck", "lint", "test", "build", "check", "db:check"])}

## Test inventory

${bullets(analysis.tests)}

## Testing and security instructions

${selectedDocs(analysis, { keywords: ["test", "security", "contributing"] }) || "No explicit testing instructions were discovered."}
`);
    files.set(`${root}/${name}/agents/openai.yaml`, openAiYaml(name, "Repository Quality", "Run the correct checks and assess risk"));
  }
  return files;
}

// existsSync + readFileSync would throw a raw EISDIR with no repository context if a directory
// happens to sit at a path where a generated file belongs — this makes that case a clear error
// (or, in currentState, simply "missing") instead of an uncaught crash.
function readExistingFile(absolute) {
  let stat;
  try {
    stat = lstatSync(absolute);
  } catch (error) {
    if (error && error.code === "ENOENT") return { exists: false, content: null };
    throw error;
  }
  if (!stat.isFile()) {
    throw new Error(`Expected a file but found a directory at ${absolute}`);
  }
  return { exists: true, content: readFileSync(absolute, "utf8") };
}

function currentState(root, files) {
  const stale = [];
  const missing = [];
  for (const [path, content] of files) {
    const absolute = join(root, path);
    const expected = `${content.trim()}\n`;
    const existing = readExistingFile(absolute);
    if (!existing.exists) {
      stale.push(path);
      missing.push(path);
    } else if (existing.content !== expected) {
      stale.push(path);
    }
  }
  return { stale, missing };
}

export async function generateSkills(analysis, options = {}) {
  const files = buildFiles(analysis);
  const { stale, missing } = currentState(analysis.root, files);
  if (options.dryRun) return { files: [...files.keys()], stale, missing, written: [] };

  const written = [];
  for (const path of stale) {
    const absolute = join(analysis.root, path);
    const existing = readExistingFile(absolute);
    if (existing.exists && !existing.content.includes(MARKER_TEXT)) {
      throw new Error(`Refusing to overwrite manual skill file: ${path}`);
    }
    await mkdir(dirname(absolute), { recursive: true });
    writeFileSync(absolute, `${files.get(path).trim()}\n`, "utf8");
    written.push(path);
  }
  return { files: [...files.keys()], stale, missing, written };
}

export function checkSkills(analysis) {
  const files = buildFiles(analysis);
  const { stale, missing } = currentState(analysis.root, files);
  return { files: [...files.keys()], stale, missing };
}
