import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

const MARKER_TEXT = "generated by claude-repo-skills; do not edit";
const MARKER = `<!-- ${MARKER_TEXT} -->`;

function frontmatter(name, description) {
  return `---\nname: ${name}\ndescription: "${description.replaceAll('"', '\\"')}"\n---`;
}

function bullets(values, empty = "None discovered.") {
  return values.length ? values.map((value) => `- \`${value}\``).join("\n") : empty;
}

function commands(analysis, wanted) {
  const scripts = analysis.package?.scripts ?? {};
  const prefix = analysis.packageManager === "npm" ? "npm run" : analysis.packageManager;
  return wanted
    .filter((name) => scripts[name])
    .map((name) => `- \`${prefix} ${name}\``)
    .join("\n") || "Use the repository-native validation commands.";
}

function selectedDocs(analysis, pattern) {
  return Object.entries(analysis.documentContent)
    .filter(([path]) => pattern.test(path))
    .map(([path, content]) => `## ${path}\n\n${content}`)
    .join("\n\n");
}

function openAiYaml(name, title, description) {
  return `# ${MARKER_TEXT}
interface:
  display_name: "${title}"
  short_description: "${description}"
  default_prompt: "Use $${name} to work with this repository."
`;
}

function buildFiles(analysis) {
  const files = new Map();
  const root = analysis.config.output;
  const stack = [
    `Repository: \`${analysis.name}\``,
    `Digest: \`${analysis.digest}\``,
    `Languages: ${Object.entries(analysis.languages).map(([name, count]) => `${name} (${count})`).join(", ") || "unknown"}`,
    `Manifests: ${analysis.manifests.map((name) => `\`${name}\``).join(", ") || "none"}`,
    `Package manager: \`${analysis.packageManager ?? "not detected"}\``,
  ].map((line) => `- ${line}`).join("\n");

  if (analysis.config.skills.includes("development")) {
    const name = "repo-development";
    files.set(`${root}/${name}/SKILL.md`, `${frontmatter(name, `Implement, refactor, or debug ${analysis.name} using its discovered architecture, module boundaries, stack, and repository conventions.`)}

${MARKER}

# Repository development

1. Read [references/repository.md](references/repository.md).
2. Inspect the target module and its public boundary.
3. Follow existing architecture and naming patterns.
4. Keep domain logic outside routing and presentation layers.
5. Add focused tests and run the repository quality gates.

Do not infer conventions when the repository documents them explicitly.
`);
    files.set(`${root}/${name}/references/repository.md`, `${MARKER}

# Repository map

${stack}

## Modules

${bullets(analysis.modules)}

## Package scripts

${bullets(Object.keys(analysis.package?.scripts ?? {}).sort())}

## Repository instructions

${selectedDocs(analysis, /(?:AGENTS|CLAUDE|architecture|code-style)/i) || "No explicit architecture instructions were discovered."}
`);
    files.set(`${root}/${name}/agents/openai.yaml`, openAiYaml(name, "Repository Development", "Follow repository architecture and conventions"));
  }

  if (analysis.config.skills.includes("domain")) {
    const name = "repo-domain";
    files.set(`${root}/${name}/SKILL.md`, `${frontmatter(name, `Design or change business behavior in ${analysis.name} using its product documentation, invariants, compliance boundaries, and domain vocabulary.`)}

${MARKER}

# Repository domain

1. Read [references/domain.md](references/domain.md).
2. Name the business invariant before changing behavior.
3. Preserve authorization, auditability, privacy, and transactional consistency.
4. Use fictitious data in tests and examples.
5. Document residual domain or compliance risk.
`);
    files.set(`${root}/${name}/references/domain.md`, `${MARKER}

# Domain context

Generated from repository documentation. Digest: \`${analysis.digest}\`.

${selectedDocs(analysis, /(?:README|AGENTS|docs\/|domain|product|security|compliance)/i) || "No domain documentation was discovered."}
`);
    files.set(`${root}/${name}/agents/openai.yaml`, openAiYaml(name, "Repository Domain", "Apply product and domain invariants safely"));
  }

  if (analysis.config.skills.includes("quality")) {
    const name = "repo-quality";
    files.set(`${root}/${name}/SKILL.md`, `${frontmatter(name, `Validate, review, or prepare changes in ${analysis.name} using its actual test commands, CI expectations, security constraints, and completion gates.`)}

${MARKER}

# Repository quality

1. Read [references/quality.md](references/quality.md).
2. Run the smallest relevant test first.
3. Preserve the first useful failure and diagnose it.
4. Run all required gates before declaring completion.
5. Report every skipped check and its reason.
`);
    files.set(`${root}/${name}/references/quality.md`, `${MARKER}

# Quality map

Generated from repository sources. Digest: \`${analysis.digest}\`.

## Required commands

${commands(analysis, ["typecheck", "lint", "test", "build", "check", "db:check"])}

## Test inventory

${bullets(analysis.tests)}

## Testing and security instructions

${selectedDocs(analysis, /(?:test|security|contributing)/i) || "No explicit testing instructions were discovered."}
`);
    files.set(`${root}/${name}/agents/openai.yaml`, openAiYaml(name, "Repository Quality", "Run the correct checks and assess risk"));
  }
  return files;
}

function currentState(root, files) {
  const stale = [];
  for (const [path, content] of files) {
    const absolute = join(root, path);
    const expected = `${content.trim()}\n`;
    if (!existsSync(absolute) || readFileSync(absolute, "utf8") !== expected) stale.push(path);
  }
  return stale;
}

export async function generateSkills(analysis, options = {}) {
  const files = buildFiles(analysis);
  const stale = currentState(analysis.root, files);
  if (options.dryRun) return { files: [...files.keys()], stale, written: [] };

  const written = [];
  for (const path of stale) {
    const absolute = join(analysis.root, path);
    if (existsSync(absolute)) {
      const current = readFileSync(absolute, "utf8");
      if (!current.includes(MARKER_TEXT)) throw new Error(`Refusing to overwrite manual skill file: ${path}`);
    }
    await mkdir(dirname(absolute), { recursive: true });
    writeFileSync(absolute, `${files.get(path).trim()}\n`, "utf8");
    written.push(path);
  }
  return { files: [...files.keys()], stale, written };
}

export function checkSkills(analysis) {
  const files = buildFiles(analysis);
  return { files: [...files.keys()], stale: currentState(analysis.root, files) };
}
